const categories = [
  {
    name: "Show All",
    filter: "all",
  },
  {
    name: "Italy",
    filter: "italy",
  },
  {
    name: "UAE",
    filter: "uae",
  },
  {
    name: "France",
    filter: "france",
  },
  {
    name: "Israel",
    filter: "israel",
  },
  {
    name: "Japan",
    filter: "japan",
  },
  {
    name: "Germany",
    filter: "germany",
  },
  {
    name: "Thailand",
    filter: "thailand",
  },
  {
    name: "Georgia",
    filter: "georgia",
  },
];

const images = [
  {
    id: "1",
    url: "gallery1.jpg",
    category: "israel",
    title:
      "Mount Tabor Nature Reserve and National Park, Lower Galilee, Israel",
    blog: "Mount Tabor is known for its beautifully round shape rising from the ground in the heart of Lower Galilee. The area is lush and green year-round, with scenic and natural values, history, and archaeological treasures. Due to its height the mountain provides spectacular views. On the Mountaintop path there are wonderful observation points. Furthermore, the mountain itself has a number of caves, some natural, which served as quarries for cutting stones to build the wall. In the northern part, under the Greek church, there is a cave the opening of which is built of chiseled stones, and it is open to visitors.",
  },
  {
    id: "2",
    url: "gallery2.jpg",
    category: "france",
    title: "Strasbourg, France ",
    blog: "Strasbourg is indeed one of Europe's most scenic cities - from the imposing Cathedral with its intricate carvings, to the picturesque houses and canals of Petite France. It is therefore very popular as a tourist destination and a wonderful place to live. There's a lot to see and do in the region, with Strasbourg as your base. Discover the vineyards, lakes and mountains, or visit the region's towns or villages.",
  },
  {
    id: "3",
    url: "gallery3.jpg",
    category: "israel",
    title: "Dead Sea, Israel",
    blog: "The Dead Sea known as the lowest place on earth. It's surrounded by the stunning landscape of the Negev desert. The saline waters of the lake means no fish can survive in the salty waters, hence the name. The other result of the salty water is their renowned health and healing properties of the mud. You can also float naturally in them.",
  },
  {
    id: "4",
    url: "gallery4.jpg",
    category: "japan",
    title: "Matsumoto Castle, Japan",
    blog: "Matsumoto Castle which also originally known as Fukashi Castle, is one of Japan's premier historic castles and is located in the city of the same name, Nagano Prefecture. My parents visited this beautiful castle among other areas in Japan few years ago and my dream is to visit this place someday as well.",
  },
  {
    id: "5",
    url: "gallery5.jpg",
    category: "italy",
    title: "Lago Di Carezza, Italy",
    blog: "Lago Di Carezza is the most beautiful lake in Dolomites, South Tyrol, well at least in my opinion. The water of emerald which sparkle magnificently with the flecks of a rainbow are completely mesmerizing and to fall in love with this place is pretty easy. Visit this place in sunrise or sunset is definitely a magical time. The lake itself small, though the size doesn't really matter as it still beats all the other lakes and by the way swimming there is prohibited. As I've heard, this wondrous place changed from the last time I've visited which was in 2013. In late 2018, a massive storm tore through Northern Italy along other countries. There were winds of more than 200km/h that ruined many forests. Lots of trees were fallen or cut which apparently caused more destruction and earnest consequences for its ecosystem. It will take a long time to fully recover from that storm. I wish there won't be anymore damage to this marvelous place that I love very much and hopefully I'll visit soon.",
  },
  {
    id: "6",
    url: "gallery6.jpg",
    category: "uae",
    title: "Dubai, UAE",
    blog: "Wow what can I say about this gorgeous place that others didn't. I've traveled to Dubai which is in United Arab Emirates or for short UAE, in last november (2022) for the first time ever, and hopefully not the last. It's been such a wonderful time there, traveled and seen a lot in just about 4-5 days. Just the day we arrived, we already went for a boat/cruise sailing in Dubai River at eve including wonderful dinner, great music, company but most of all great scenery. Dubai has a lot to offer, a lot to see and experience, a lot to explore and feel, from the magnificent viewpoint at Burj Khalifa that is known for being the world's tallest building, to Dubai gorgeous marina, the 360 deg panoramic view at the Palm Observatory, to the gorgeus Dubai desert and yes it is gorgeous beauty of sand that I love. Reaching by the train above water at some part, to the magnificent Palm Jumeirah island, it's the time when you just can't stop rubbing your eyes because of the view around you and mainly because this luxory hotel and obviously not cheap lol.",
  },
  {
    id: "7",
    url: "gallery7.jpg",
    category: "italy",
    title: "Sirmione, Italy",
    blog: "",
  },
  {
    id: "8",
    url: "gallery8.jpg",
    category: "japan",
    title: "Kinkaku-Ji Temple, Kyoto, Japan",
    blog: "",
  },
  {
    id: "9",
    url: "gallery9.jpg",
    category: "italy",
    title: "Rio di San Felice, Venezia, Italy",
    blog: "",
  },
  {
    id: "10",
    url: "gallery10.jpg",
    category: "germany",
    title: "State Museum of Baden, Karlsruhe Palace, Germany",
    blog: "",
  },
  {
    id: "11",
    url: "gallery11.jpg",
    category: "germany",
    title: "Heidelberg, Germany",
    blog: "",
  },
  {
    id: "12",
    url: "gallery12.jpg",
    category: "japan",
    title: "Statue of Liberty and Rainbow bridge in Odaiba, Tokyo, Japan",
    blog: "",
  },
  {
    id: "13",
    url: "gallery13.jpg",
    category: "georgia",
    title: "Batumi, Georgia",
    blog: "",
  },
  {
    id: "14",
    url: "gallery14.jpg",
    category: "thailand",
    title: "Phuket, Thailand",
    blog: "",
  },
  {
    id: "15",
    url: "gallery15.jpg",
    category: "japan",
    title: "Tokyo Skyline view, Japan",
    blog: "",
  },
  {
    id: "16",
    url: "gallery16.jpg",
    category: "france",
    title: "Colmar, France",
    blog: "",
  },
  {
    id: "17",
    url: "gallery17.jpg",
    category: "georgia",
    title: "Batumi, Georgia",
    blog: "",
  },
  {
    id: "18",
    url: "gallery18.jpg",
    category: "uae",
    title: "Miracle Garden, Dubai, UAE",
    blog: "",
  },
  {
    id: "19",
    url: "gallery19.jpg",
    category: "uae",
    title: "The Frame, Dubai, UAE",
    blog: "",
  },
  {
    id: "20",
    url: "gallery20.jpg",
    category: "thailand",
    title: "Doi Tung Palace, Mae Fa Luang, Thailand",
    blog: "",
  },
  {
    id: "21",
    url: "gallery21.jpg",
    category: "thailand",
    title: "Nongnooch Pattaya Garden and Resort, Thailand",
    blog: "",
  },
];
